apiVersion: v1
kind: ConfigMap
metadata:
    name: benchmark-config
data:
    benchmark.properties: |
        test.type=datastream
        test.schema=json
        test.semantic=exactly-one
        test.parallelism=2
        test.partitions=4
        test.subscription-mode=lExclusive