apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
    namespace: flink-sql
    name: benchmark-flink-session-cluster
spec:
    image: affe/pulsar-flink-benchmark-demo:latest
    imagePullPolicy: Always
    flinkVersion: v1_15
    flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
    serviceAccount: flink
    podTemplate:
        apiVersion: v1
        kind: Pod
        metadata:
            name: pod-template
        spec:
            serviceAccount: flink
            containers:
                # Do not change the main container name
                - name: flink-main-container
                  volumeMounts:
                      - mountPath: /opt/flink/plugins/benchmark/config
                        name: benchmark-config
                        readOnly: true
            volumes:
                - name: benchmark-config
                  configMap:
                      optional: true
                      name: benchmark-config
                      items:
                      - key: "benchmark.properties"
                        path: "benchmark.properties"
    jobManager:
        resource:
            memory: "2048m"
            cpu: 1
    taskManager:
        resource:
            memory: "2048m"
            cpu: 1

