apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
    namespace: flink-sql
    name: flink-benchmark
spec:
    image: affe/pulsar-flink-benchmark-demo:1.0.0
    flinkVersion: v1_15
    flinkConfiguration:
        taskmanager.numberOfTaskSlots: "2"
    serviceAccount: flink
    jobManager:
        resource:
            memory: "2048m"
            cpu: 1
    taskManager:
        resource:
            memory: "2048m"
            cpu: 2
    job:
        jarURI: local:///opt/flink/examples/flink-sql-connector-pulsar-demo-1.0-SNAPSHOT.jar
        parallelism: 2
        upgradeMode: stateless
        state: running

